import type { Metadata } from 'next'
import { Outfit } from 'next/font/google' // Importando a fonte corretamente
import './globals.css'

// Carregando a fonte Outfit
const outfit = Outfit({
  subsets: ['latin'],
  weight: ['300', '400', '600', '700'], // Defina os pesos necessários
})

// Metadados para SEO
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} antialiased h-full`}>
        {children}
      </body>
    </html>
  )
}
